#!/usr/bin/env python
"""add floating point numbers on each line in first file and write total to second file"""

import sys

total = 0.0
with open(sys.argv[1], 'r') as f:
    for line in f:
        total += float(line)

with open(sys.argv[2], 'w') as f:
    f.write("{:f}\n".format(total))
